// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/client/client.proto

package client

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Client service

func NewClientEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Client service

type ClientService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Client_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Client_PingPongService, error)
}

type clientService struct {
	c    client.Client
	name string
}

func NewClientService(name string, c client.Client) ClientService {
	return &clientService{
		c:    c,
		name: name,
	}
}

func (c *clientService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Client.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Client_StreamService, error) {
	req := c.c.NewRequest(c.name, "Client.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &clientServiceStream{stream}, nil
}

type Client_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type clientServiceStream struct {
	stream client.Stream
}

func (x *clientServiceStream) Close() error {
	return x.stream.Close()
}

func (x *clientServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *clientServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *clientServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *clientServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientService) PingPong(ctx context.Context, opts ...client.CallOption) (Client_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Client.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &clientServicePingPong{stream}, nil
}

type Client_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type clientServicePingPong struct {
	stream client.Stream
}

func (x *clientServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *clientServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *clientServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *clientServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *clientServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *clientServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Client service

type ClientHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Client_StreamStream) error
	PingPong(context.Context, Client_PingPongStream) error
}

func RegisterClientHandler(s server.Server, hdlr ClientHandler, opts ...server.HandlerOption) error {
	type client interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Client struct {
		client
	}
	h := &clientHandler{hdlr}
	return s.Handle(s.NewHandler(&Client{h}, opts...))
}

type clientHandler struct {
	ClientHandler
}

func (h *clientHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ClientHandler.Call(ctx, in, out)
}

func (h *clientHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ClientHandler.Stream(ctx, m, &clientStreamStream{stream})
}

type Client_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type clientStreamStream struct {
	stream server.Stream
}

func (x *clientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *clientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *clientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *clientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *clientStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *clientHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ClientHandler.PingPong(ctx, &clientPingPongStream{stream})
}

type Client_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type clientPingPongStream struct {
	stream server.Stream
}

func (x *clientPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *clientPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *clientPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *clientPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *clientPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *clientPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
